services:
  backend:
    build:
      context: .
    image: backend
    ports:
      - '5000:5000'
    restart: always
    network_mode: host
    environment:
      - NODE_EN=preprod
      - PORT=5000